boilerplate.creativeorange.dev:
  stage: staging
  hostname: 37.97.231.5
  deploy_path: ~/apps/boilerplate/
  branch: development
  user: creativeorange
  repository: git@bitbucket.org:creativeorange/boilerplate-craft-4.git
  shared_files:
    - .env
  shared_dirs:
    - storage
    - web/upload
  clear_paths:
    - node_modules
  bin/php: php7.4-sp
  bin/composer: composer7.4-sp
  bin/npm: npm
